name: Run tests

on: pull_request

jobs:
  tests:
    name: Tests
    runs-on: macOS-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install bundle
        run: bundle install

      - name: Build and Test
        run: bundle exec fastlane ios tests