name: Run tests

on: pull_request

jobs:
  tests:
    name: Tests
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app

      - name: Install bundle
        run: bundle install

      - name: Build and Test
        run: bundle exec fastlane ios tests
