name: Run tests

on: pull_request

jobs:
  tests:
    name: Tests
    runs-on: macOS-latest

    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,OS=13.7,name=iPhone 8'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app

      - name: Install bundle
        run: bundle install

      - name: Build and Test
        run: bundle exec fastlane ios tests
        env:
          destination: '${{ matrix.destination }}'
